name: todo_list_app
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  material_color_utilities: 0.11.1
  vector_math: 2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  async: ^2.12.0 # Menggunakan versi yang sesuai dengan flutter_test
  fake_async: 1.3.2
  leak_tracker: 10.0.8
  leak_tracker_flutter_testing: 3.0.9
  leak_tracker_testing: 3.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
